// GET all
http://localhost:8081/api/v1
Content-Type: application/json
GET /books

// GET one by id
http://localhost:8081/api/v1
Content-Type: application/json
GET /books/2

// CREATE 1
http://localhost:8081/api/v1
Content-Type: application/json
POST /books
{
"sku":"113",
"title":"Harry Potter a kamen mudrcu",
"author":"J. K. Rowling",
"description":"O sutru.",
"price":119.90
}

// CREATE 1
http://localhost:8081/api/v1
Content-Type: application/json
POST /books
{
"sku":"759",
"title":"Harry Potter a ohnivy pohar",
"author":"J. K. Rowling",
"description":"O poharu.",
"price":119.90
}

// UPDATE by id
http://localhost:8081/api/v1
Content-Type: application/json
PUT /books/26
{
    "author":"Emily Bronteova"
}

// DELETE by id
http://localhost:8081/api/v1
Content-Type: application/json
DELETE /books/2

// RECOVER by id
http://localhost:8081/api/v1
Content-Type: application/json
POST /books/2/recover
